### ISSUE TITLE
Missing license file

### ISSUE THREAD

**Issue by ajkl2533** [zhaosiyang/axios-observable#1]
@zhaosiyang Hi is it possible to add LICENSE file inside the repo and release new patch version with the license?

MIT License requires to distribute full license text along the source code so right now this is actually proprietary code and cannot be legally used by anyone.

So if you would be able to add LICENSE.md file with this text https://opensource.org/licenses/MIT it would be great.

Thanks a lot

**Comment by zhaosiyang** [comment]
@ajkl2533 Thanks for your feedback. I have added MIT license to the repo.
