### ISSUE TITLE
I get a warning about cancel tokens that I'm not even trying to use

### ISSUE THREAD

**Issue by insidewhy** [zhaosiyang/axios-observable#11]
I get the error: "No need to use cancel token, just unsubscribe the subscription would cancel the http request automatically"

I'm just using `Axios.get(url, { httpsAgent: new https.Agent({ rejectUnauthorized: false } })`, no cancel tokens.

**Comment by insidewhy** [comment]
It seems that any attempt to use the `options` parameter causes this error :(

EDIT: Happens only when you reuse the same options argument across multiple requests.

**Comment by insidewhy** [comment]
Ah I see, it's because the library mutates the options argument that was passed to it. If you pass the same options argument again, you get this error. It should probably make a copy.

**Comment by xenovon** [comment]
I only get exactly 1 result when try to search my problem on google, lead me to this issue. Fortunately, this is exactly the one that I need.  Thank you very much @ohjames. You saved me potentially hours of headache.

**Comment by zhaosiyang** [comment]
Thanks for reporting this issue, it's now fixed
