### ISSUE TITLE
Lambda execution failed. Error: Cannot find module 'axios-observable' 

### ISSUE THREAD

**Issue by middoors** [zhaosiyang/axios-observable#15]
Lambda execution failed with status 200 due to customer function error: Error: Cannot find module 'axios-observable' Require stack: - /var/task/src/handlers/handler.js - /var/runtime/UserFunction.js - /var/runtime/index.js. Lambda request id: cac503cb-a8eb-4031-b472-3df40dc53857

**Comment by zhaosiyang** [comment]
Thanks for reporting. This is probably a Lambda config error, which is out of scope of this library.
