### ISSUE TITLE
- Upgrade Axios into 0.21.1

### ISSUE THREAD

**Issue by xenovon** [zhaosiyang/axios-observable#18]
I got a build error because Axios that this package use is still using Axios 0.19, which has an SSRF vulnerability.  

![image](https://user-images.githubusercontent.com/706301/103902401-0ee1f680-512d-11eb-971d-e5b5f959a4e5.png)

This security hole is fixed in the latest version of Axios:  https://github.com/axios/axios/pull/3410

Do you mind to update the Axios version to 0.21.1?

**Comment by zhaosiyang** [comment]
Done and published v1.1.6. Thank you

**Comment by xenovon** [comment]
Thank you!
