### ISSUE TITLE
Mocking axios-observable with Jest

### ISSUE THREAD

**Issue by Foetus6907** [zhaosiyang/axios-observable#19]
I have an issue when i try to mock axios-observable with jest.
`jest.mock("axios-observable", () => Object.assign(
	jest.fn(),
	{ get: jest.fn() }
));`

Here's how i try to mock it.
But i got an error when executing my test saying :
'TypeError: _axiosObservable.default.get(...).pipe is not a function'
Any idea of what going wrong or any exemple of mocking exemple implementation ?

Thanks by advance,
Best Regards

**Comment by mkoert** [comment]
Is there a reason this is closed? Is there an example on how to do this correctly then?

**Comment by ItaloMedici** [comment]
Any update?
