### ISSUE TITLE
'axios-observable'. CommonJS or AMD dependencies can cause optimization bailouts

### ISSUE THREAD

**Issue by t-model00291182** [zhaosiyang/axios-observable#21]
Hello,

I'm using this nice package, but i goth this warning

![image](https://user-images.githubusercontent.com/5758829/113543770-5b7f8580-95e7-11eb-9770-39e4020f52ae.png)

I want to ask if you want to upgrade _tsconfig_ and set target to `es2015` or `es2016` and module maybe to `es2020` or `esnext`?

**Comment by zhaosiyang** [comment]
@Michel00291182 Changed to `es2015` in version 1.2.1
Thank you for your feedback
