### ISSUE TITLE
Doesn't work with the latest Axios 1.1.3 (wants 0.27.0)?

### ISSUE THREAD

**Issue by lasertiger** [zhaosiyang/axios-observable#32]
Hi! Seems axios-observable wants a very old version of axios (0.27.0) -- could this be updated?

node: v18.4.0
npm:8.19.2

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @xxx/xxx:
npm ERR! Found: axios@1.1.3
npm ERR! node_modules/axios
npm ERR!   axios@"^1.1.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer axios@"^0.27.0" from axios-observable@1.5.0
npm ERR! node_modules/axios-observable
npm ERR!   axios-observable@"*" from the root project

**Comment by zhaosiyang** [comment]
@lasertiger Thanks for the feedback. It's being worked on. Stay tuned!

**Comment by zhaosiyang** [comment]
Blocked by an issue in axios https://github.com/axios/axios/issues/5174

**Comment by JoseLion** [comment]
@zhaosiyang the issue with axios shouldn't be a problem. I think you just need to add the following to your tsconf.json and you should be good to go 🙂 
```jsonc
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    // ...rest of compiler options
  }
}
```

**Comment by zhaosiyang** [comment]
#33 Merged. axios-observable@2.0.0 published
