### ISSUE TITLE
Export AxiosResponse through 'axios-observable';

### ISSUE THREAD

**Issue by JasonLandbridge** [zhaosiyang/axios-observable#34]
Hi there, 

Is it possible to re-export all the typings, such as AxiosResponse, that come from the axios inside axios-observable so we can use it like this:

```typescript
import Axios, { AxiosResponse} from 'axios-observable';

Axios.get<string>(`some-url`).pipe(map((res: AxiosResponse) => res?.data));
```

Currently you can do it like the following:
```typescript
import { AxiosResponse } from 'axios';
import Axios from 'axios-observable';

Axios.get<string>(`some-url`).pipe(map((res: AxiosResponse) => res?.data));
```

But that requires the extra axios package to be installed like this:

```json
"axios": "^1.2.0",
"axios-observable": "^2.0.0",
```

Deploying the application will fail due to missing typings if the axios is not installed seperatly.

Anyway, great tool and thanks for all the work!

**Comment by zhaosiyang** [comment]
Hi @JasonLandbridge Thanks for the feedback. 

Please note that the two packages `axios` and `rxjs` are specified as peer dependencies so you have to install `axios` to make it working anyway.

I am not a fan of re-exporting `AxiosResponse` as it confuses people where to import. I would prefer to import from `axios` directly to give developers a clear signal that axios-observable would return exact same object as axios.
